### ISSUE TITLE
Supporting sample rate.

### ISSUE THREAD

**Issue by kibumh** [chrisstaite/lameenc#1]
Hi. I tried to find a python module which encodes pcm data into a mp3 format, and this is the only thing that matches my requirement. (Thanks for this project!)

One thing I'm missing is a sample rate support. Is there any reason that you only support 44.1kHz as sample rate? Do you mind if I send a PR?

**Comment by chrisstaite** [comment]
I built this as a quick fix for a project I had that needed it.  There was very little in the way of making features other than it just working. I'm always very happy for pull requests.


On 29 August 2019 02:35:31 BST, kibumh <notifications@github.com> wrote:
>Hi. I tried to find a python module which encodes pcm data into a mp3
>format, and this is the only thing that matches my requirement. (Thanks
>for this project!)
>
>One thing I'm missing is a sample rate support. Is there any reason
>that you only support 44.1kHz as sample rate? Do you mind if I send a
>PR?
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/chrisstaite/lameenc/issues/1

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
