### ISSUE TITLE
Build is broken on Windows for Python3.9

### ISSUE THREAD

**Issue by adefossez** [chrisstaite/lameenc#12]
Hi @chrisstaite, first a huge thank for this project, it is really awesome to be able to write MP3 on all platform with such a small dependency!!

I noticed that the most recent build for Python3.9 on Windows is not available, and it seems the build is broken.

**Comment by leonbloy** [comment]
Indeed. I can't install this with Python 3.9 in Windows 10

```
> pip install lameenc
ERROR: Could not find a version that satisfies the requirement lameenc (from versions: none)
ERROR: No matching distribution found for lameenc
>pip -V
pip 21.1.2 from c:\python39\lib\site-packages\pip (python 3.9)
```

**Comment by chrisstaite** [comment]
I think the answer is in here somewhere: https://stackoverflow.com/questions/63750020/unresolved-external-symbol-error-when-linking-a-cython-extension-against-a-c-l
However, I have no idea why VS2019 is so awkward or mangling names differently for the two separate C projects.

**Comment by chrisstaite** [comment]
Turns out it was a missing NOT.

**Comment by adefossez** [comment]
Thank you so much for the fix @chrisstaite !
