### ISSUE TITLE
Can't Build for Jeston Nano 2GB (armv8 64 bits)

### ISSUE THREAD

**Issue by fercamp09** [chrisstaite/lameenc#16]
Hello, I was trying to build the project using make within the Jetson Nano running Ubuntu and this was the output.

/lib/lameenc/build$ sudo make
Scanning dependencies of target lame
[ 10%] Creating directories for 'lame'
[ 20%] Performing download step (download, verify and extract) for 'lame'
-- Downloading...
   dst='/lib/lameenc/build/lame/src/lame-3.100.tar.gz'
   timeout='none'
-- Using src='https://sourceforge.net/projects/lame/files/lame/3.100/lame-3.100.tar.gz/download'
-- verifying file...
       file='/lib/lameenc/build/lame/src/lame-3.100.tar.gz'
-- Downloading... done
-- extracting...
     src='/lib/lameenc/build/lame/src/lame-3.100.tar.gz'
     dst='/lib/lameenc/build/lame/src/lame'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[ 30%] Performing patch step for 'lame'
[ 40%] No update step for 'lame'
[ 50%] Performing configure step for 'lame'
checking build system type... aarch64-unknown-linux-gnu
checking host system type... aarch64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
 ...

Making install in vc_solution
[ 80%] Completed 'lame'
[ 80%] Built target lame
Scanning dependencies of target library3.7
[ 90%] Generating lameenc-1.0.0-cp37-cp37m-linux_x86_64.whl
/usr/lib/python3/dist-packages/setuptools/[dist.py:397](https://dist.py:397/): UserWarning: Normalizing 'v1.3.1' to '1.3.1'
  normalized_version,
running bdist_wheel
running build
running build_ext
building 'lameenc' extension
creating build/temp.linux-aarch64-3.7
aarch64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/lib/lameenc/build/lame/src/lame/include -I/usr/include/python3.7m -c lameenc.c -o build/temp.linux-aarch64-3.7/lameenc.o
lameenc.c:3:10: fatal error: Python.h: No such file or directory
 [#include](tg://search_hashtag?hashtag=include) <Python.h>
          ^~~~~~~~~~
compilation terminated.
error: command 'aarch64-linux-gnu-gcc' failed with exit status 1
CMakeFiles/library3.7.dir/build.make:61: recipe for target 'lameenc-1.0.0-cp37-cp37m-linux_x86_64.whl' failed
make[2]: *** [lameenc-1.0.0-cp37-cp37m-linux_x86_64.whl] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/library3.7.dir/all' failed
make[1]: *** [CMakeFiles/library3.7.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Ends with this error:`error: command 'aarch64-linux-gnu-gcc' failed with exit status 1. CMakeFiles/library3.7.dir/build.make:61: recipe for target 'lameenc-1.0.0-cp37-cp37m-linux_x86_64.whl' failed`

Somehow it is not recognizing the armv8 64 bit (CPU | Quad-core ARM® A57 @ 1.43 GHz) and maybe is trying to compile for x86_64.

What can I do to make it work?

**Comment by chrisstaite** [comment]
You need to install the python-dev package
