### ISSUE TITLE
Encoder not initialised when trying to encode audio

### ISSUE THREAD

**Issue by Tomsen1410** [chrisstaite/lameenc#17]
I'm trying to use this library in Google Colab. However it throws the following error when using the example from the main page:

```
File "../tmp_resampler.py", line 40, in run
    mp3data = encoder.encode(audio)
RuntimeError: Encoder not initialised
```

I've simply installed it with `pip install lameenc`

**Comment by chrisstaite** [comment]
Please give a complete example of how you are producing this error. It is impossible for it to occur on a first calling of encode. Perhaps you are re-using an encoder more than once?

**Comment by chrisstaite** [comment]
That's the best way to do it.
