### ISSUE TITLE
Unable to install version 1.4.1 via pip

### ISSUE THREAD

**Issue by xserrat** [chrisstaite/lameenc#18]
I'm trying to install the latest `lameenc` version that supports arm64 via pip:

```bash
pip install lameenc==1.4.1
```

But I get this error:

```
ERROR: Could not find a version that satisfies the requirement lameenc==1.4.1 (from versions: none)
```

I'm using pip version `22.3.1`.

As a workaround, I tried to install it using the `.zip`
```bash
pip install https://github.com/chrisstaite/lameenc/archive/refs/tags/v1.4.1.zip
```
but it seems I have to specify some inputs:
![image](https://user-images.githubusercontent.com/5933658/204132093-d17c4082-ae2f-4428-9ecf-d2d4f09be23e.png)

Any idea? Thanks 🙏🏽

**Comment by chrisstaite** [comment]
Which version of python are you running?

**Comment by xserrat** [comment]
I'm running python 3.8

**Comment by xserrat** [comment]
> Which version of python are you running?

I'm running python 3.8

**Comment by chrisstaite** [comment]
What happens if you try and install https://files.pythonhosted.org/packages/c7/64/21fea98d613bde39084d9ff5d7fc86750c04d7da88555c9003d06154ffc7/lameenc-1.4.1-cp38-cp38-macosx_11_0_arm64.whl

**Comment by chrisstaite** [comment]
Oh, you're running Linux ARM64.  I haven't got a build for that currently.  I tried for a bit but couldn't get it to work.  You need to build using cmake (see https://github.com/chrisstaite/lameenc#build)

**Comment by xserrat** [comment]
Oh ok, no problem at all! That's just what I've done and works great 👏🏽

Thanks for your quick reply!

**Comment by chrisstaite** [comment]
I think I've figured out Linux ARM64 building now anyway.  So will be publishing new ARM64 Wheels for ARM64 and Python 3.11.

**Comment by xserrat** [comment]
That's great news! I'll stay tuned to try it out.

**Comment by chrisstaite** [comment]
All built and published on version 1.4.2 now.

**Comment by xserrat** [comment]
Cool, using Python 3.11, right?

**Comment by chrisstaite** [comment]
Support for Python 3.7 to 3.11.

**Comment by xserrat** [comment]
It's weird because I'm still getting the same error:

```
ERROR: Could not find a version that satisfies the requirement lameenc==1.4.2 (from versions: none)
ERROR: No matching distribution found for lameenc==1.4.2
````
It could be from my side. I'm running a Dockerfile to install this library using version 3.8 and also tested with 3.11 ( https://github.com/xserrat/docker-facebook-demucs/actions/runs/3558390634/jobs/5977022903#step:7:393)

I will check my dependencies because maybe I'm missing something.

**Comment by chrisstaite** [comment]
I'd have thought this would have matched that environment? https://files.pythonhosted.org/packages/81/6a/77878a527d6be4ced99a7e328fa132de20b75b9a20e0d3e181284b51ed1d/lameenc-1.4.2-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.manylinux_2_24_aarch64.whl

**Comment by xserrat** [comment]
It should be... it's an alpine image (`python:3.11-alpine3.15`) but it fails for amd. I don't know why :/ building it on my own works perfectly.
