### ISSUE TITLE
lameenc slower than lame binary?

### ISSUE THREAD

**Issue by t-dan** [chrisstaite/lameenc#20]
I have tried lameenc and compared it to the direct invocation of lame binary through the subprocess module.
The lameenc is slower for the same quality and bitrate, although I expected the opposite (binary invocation + initialization and passing data through pipes needs some time, doesn't it?). 

Do you have an idea why it is? Are there any build options to be switched on?

**Comment by chrisstaite** [comment]
I haven't personally done any benchmarking. Could you show your methodology please?

I don't know of any compiler flags for LAME that might improve performance, but I haven't looked in depth.

I can't see how the library code itself might be less efficient than an external call. How much slower is it?

This library is mostly about convenience rather than efficiency, however that's not to say it's slow on purpose.

**Comment by t-dan** [comment]
Here is a testing script ... Hopefully, it will work.
```
#!/usr/bin/python3

import timeit
import threading
import subprocess
from scipy.io import wavfile

import lameenc

def read_wav() :
    sr,data = wavfile.read('pokus.wav')
    return data

def sink(data, output) :
    output.extend(data)


def encode1(data) :
    lame = lameenc.Encoder()
    lame.set_in_sample_rate(22050)
    lame.set_channels(1)
    lame.set_bit_rate(112) # lame default
    lame.set_quality(3)    # lame default, 2-highest, 7-fastest

    out = bytearray()
    out += lame.encode(data)


def encode2(data) :
    comand = ("/usr/bin/lame", "-r", "-s", '22050', "-m", "m", "-", "-", "-c", "--cbr", "-b", "112")

    def stdout(process, out):
        while True:
            data = process.stdout.read(1024)
            if not data:
                break
            out.extend(data)

    def stderr(process):
        for l in process.stderr.readlines() :
            pass

    out = []
    process = subprocess.Popen(comand, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    outpumper = threading.Thread(target=stdout, args = (process, out))
    outpumper.start()
    errpumper = threading.Thread(target=stderr, args = (process, ))
    errpumper.start()

    process.stdin.write(data)
    process.stdin.close()

    outpumper.join()
    errpumper.join()


# # Try
# data = read_wav()
# # print(data)
#
# # Encode
# out = encode1(data)
# # print(len(out), out[1:10])
#
# out = encode2(data)
# # print(len(out), out[1:10])


if __name__ == '__main__':
    import timeit

    print('lameenc')
    print(timeit.timeit("encode1(data)", setup="from __main__ import read_wav,encode1; data = read_wav()", number=1000))

    print('/usr/bin/lame')
    print(timeit.timeit("encode2(data)", setup="from __main__ import read_wav,encode2; data = read_wav()", number=1000))
```

**Comment by chrisstaite** [comment]
Looks like there is an option --enable-expopt, I'm not sure what options are used to build the packaged lame, I wonder if there's a way to find out.

**Comment by chrisstaite** [comment]
Experimenting with the optimisations, I don't see an obvious improvement at all.  It seems that it's around 25% slower without the going though the command line tool.  And checking the flame graph, you're right that a lot of that time is actually not even spent in the encoder in the command line version.  But I'm stumped as to a reason for it.

**Comment by chrisstaite** [comment]
I found the issue :). It was removing optimisation due to two bugs, one in my code, one in the configure script of lame itself.  This only affected Linux and macOS.  Just running some test builds and then I'll ship a new version.

**Comment by chrisstaite** [comment]
I re-ran the test script above with a 2mb input file and got the following results:

```
lameenc
133.13201638599276
/usr/bin/lame
208.16149893499096
```

**Comment by t-dan** [comment]
Great! Thank you very much.
