### ISSUE TITLE
Considering releasing under LGPL license?

### ISSUE THREAD

**Issue by adefossez** [chrisstaite/lameenc#21]
Hello @chrisstaite,
Thanks again for this great library, really convenient and working on all OSes.

I am writing today to ask if you would consider releasing this package under the LGPL library ? Unless you are really attached to the GPL, this would allow a much broader usage of the library, in particular in MIT/BSD code. The original Lame Library is itself released under the LGPL so that could work.

At the moment I am using lameenc in [the Demucs source separation package](https://github.com/facebookresearch/demucs) in order to enable export as mp3s. Demucs is released under the MIT license, and the GPL license is most likely not compatible with this.

See e.g. https://github.com/facebookresearch/demucs/issues/519.

**Comment by chrisstaite** [comment]
I'm not really sure why I didn't in the first place.

**Comment by adefossez** [comment]
thanks a lot @chrisstaite for the super quick change :)
