### ISSUE TITLE
Linux - ImportError: /usr/local/lib/python3.8/site-packages/lameenc.cpython-38-x86_64-linux-gnu.so: undefined symbol: __pow_finite

### ISSUE THREAD

**Issue by JeffreyCA** [chrisstaite/lameenc#22]
Importing lameenc 1.6.0 in a Linux container fails with the following error:

```
ImportError: /usr/local/lib/python3.8/site-packages/lameenc.cpython-38-x86_64-linux-gnu.so: undefined symbol: __pow_finite
```

Here's a simple repro using a vanilla Python image:

1. `docker run -it python:3.8-bullseye bash`
2. Install lameenc: `pip3 install lameenc==1.6.0`
3. Start Python shell and `import lameenc`

Result:
```sh
root@c5eb586b6fc4:/# python
Python 3.8.17 (default, Jul 28 2023, 06:08:27) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lameenc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /usr/local/lib/python3.8/site-packages/lameenc.cpython-38-x86_64-linux-gnu.so: undefined symbol: __pow_finite
```

Versions prior to 1.6.0 seem to work fine.

**Comment by chrisstaite** [comment]
Apparently this is a clang bug with the optimisations: https://reviews.llvm.org/D74712. I'll have to disable fast-math for Linux.

**Comment by chrisstaite** [comment]
I have disabled fast-math on Linux in 1.6.1, should be available on pypi in around 10 minutes.

**Comment by chrisstaite** [comment]
Just confirmed it's working in the container as above.

**Comment by JeffreyCA** [comment]
Working on my end as well, thanks for the quick fix!
