### ISSUE TITLE
Encoding adds extra silence as prefix

### ISSUE THREAD

**Issue by CorentinJ** [chrisstaite/lameenc#23]
I have this issue where the encoding process adds an extra bit of silence at the start of the output mp3. Its duration is:
- 40ms for 16kHz
- 20ms for 32kHz
- 14ms for 48kHz

I am running on win10 with version package version 1.6.0.

Here is the code I used, do tell me if you wish to have a reproducible example as well:
```
import lameenc
from pathlib import Path

wav = load_wav("debug_01.wav", 16000)[0]
pcm16 = encode_pcm16(wav)

encoder = lameenc.Encoder()
encoder.set_bit_rate(128)
encoder.set_in_sample_rate(16000)
encoder.set_channels(1)
encoder.set_quality(2) 
mp3_bytes = encoder.encode(pcm16)
mp3_bytes += encoder.flush()

Path("b.mp3").write_bytes(mp3_bytes)

wav_bytes = WavEncoder(16000).encode_header()
wav_bytes += pcm16

Path("a.wav").write_bytes(wav_bytes)
```

[A zip archive of the input and output](https://github.com/chrisstaite/lameenc/files/12737110/in_out.zip)

Audacity visualization:
![image](https://github.com/chrisstaite/lameenc/assets/12038136/11fd6748-a906-4e17-8a3b-ad3b945a3761)

**Comment by jsalsman** [comment]
> the encoding process adds an extra bit of silence at the start of the output mp3

See https://lame.sourceforge.io/tech-FAQ.txt

**Comment by chrisstaite** [comment]
Thanks @jsalsman
