### ISSUE TITLE
Python 3.12 support

### ISSUE THREAD

**Issue by oevesque** [chrisstaite/lameenc#24]
Hi,
I'm trying to install on a new computer but I've got the error : 

```
pip install lameenc
ERROR: Could not find a version that satisfies the requirement lameenc (from versions: none)
ERROR: No matching distribution found for lameenc
```

Any Ideas ?

Windows 11
python 3.12.0
CPU: AMD 7850x3D.

**Comment by chrisstaite** [comment]
I haven't updated for 3.12 yet. Will be soon. In the mean time you can downgrade to 3.11.
