### ISSUE TITLE
Hearable click at the start of an encoded audio

### ISSUE THREAD

**Issue by freetz13** [chrisstaite/lameenc#4]
```python
import lameenc
encoder = lameenc.Encoder()
encoder.set_bit_rate(128)  # any
encoder.set_in_sample_rate(16000) # any
encoder.set_channels(2)  # any
encoder.set_quality(2)  # any
mp3_data = encoder.encode(any_interleaved_pcm_data)
mp3_data += encoder.flush()
```

`mp3_data` contains hearable click at the start. If I use cli `lame` tool, there's no clicks.

**Comment by chrisstaite** [comment]
Are you sure you've not read the header in from your PCM file as detailed in this question: https://stackoverflow.com/questions/12346314/click-sound-at-the-beginning-when-using-lame
