### ISSUE TITLE
Using lameenc with Python

### ISSUE THREAD

**Issue by davecross01** [chrisstaite/lameenc#5]
I'm new to Python, so apologies if this is a lame lameenc question. I would like to use lameenc to convert .wav files to .mp3, but I cannot even get past "import lameenc" line in my Python code, and I cannot find any useful help after a lot of searching online. What do I need to install and how? "pip install lameenc" says it cannot find anything. I'm using Python 3.8 and PyCharm in Windows 10. lameenc looks good, but I don't know how to get started and try it out.
Here is what I get from pip install lameenc in a CMD window running as Administrator:
C:\WINDOWS\system32>pip install lameenc
ERROR: Could not find a version that satisfies the requirement lameenc (from versions: none)
ERROR: No matching distribution found for lameenc

**Comment by chrisstaite** [comment]
Python 3.8 wasn't being built for.  I have added a build for Python 3.8 now and had to remove Python 3.4 support as Twine no longer supports it.
