### ISSUE TITLE
Build For Pydroid 3

### ISSUE THREAD

**Issue by web-cpu-test** [chrisstaite/lameenc#8]
Hello Chris Staite...

I am working on an TTS ( text to speech )
api for which i really need an good , platform independent wav to mp3 encoder then i come across lameenc
and this is what i need.

it works on all platforms but i am trying to build its wheel for Pydroid3 ( android python3 emulator ) it has support for cython so i know it will work.

but i am not able to figure it out that what is that file libmp3lame.a and where it is.

it will be great if you add all the necessary files to build the package like libmp3lame.a and include dirs of lame library so it will be easy to build.
or add a detailed documentation for building it on
 
here is a screenshot of pydroid3 running setup.py 
i have provided paths to dirs but they do not hahe that libmp3lame.a file
i have downloaded lame from sourceforge.net

![Screenshot_20210105-202444_Pydroid 3](https://user-images.githubusercontent.com/74465117/103660963-32256e00-4f94-11eb-84fe-9873a8acf252.jpg)

At last i would like to thank you for your work

**Comment by chrisstaite** [comment]
You should use the CMake build too compile lame which will then pass it to the setup.py correctly.
